name: test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl:
          [
            "5.40",
            "5.38",
            "5.32",
            "5.30",
            "5.28",
            "5.24",
            "5.18",
          ]
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: Install dependencies
        run: cpanm -nq --installdeps --with-recommends .
      - name: Run test
        run: prove -lrv t

